layout: default
title: ZeroG
email: zerogprinters@gmail.com
description: ZeroG Official Documentation
baseurl: "/docs"
url: "https://zerogdesign.github.io/"
github_username:  ZeroGDesign

markdown: kramdown
remote_theme: benbalter/retlab
color_scheme: dark
search_enabled: true
search.button: true
plugins:
  - jekyll-feed