title: "ZeroG Documentation"
tagline: Documentation for ZeroG printers
description: ZeroG Official Documentation
logo: "/assets/images/logo-zerog.svg"
baseurl: ""
markdown: kramdown
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: "zerog"
search_enabled: true
aux_links:
  "GitHub":
    - "//github.com/ZeroGDesign/Mercury"
aux_links_new_tab: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/images/rtfm.pngy